---
# tasks file for common

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
   - tig
   - curl
   - tree
   - htop

- include_tasks: "{{ ansible_pkg_mgr }}.yml"
