---
# tasks file for golang
# Instructions from https://golang.org/doc/install#install

- name: Check previous installation at /usr/local/go
  stat:
    path: /usr/local/go
  register: st

- name: Download & Install Go binary
  unarchive:
    src: "https://dl.google.com/go/go{{ version }}.{{ ansible_system | lower }}-amd64.tar.gz"
    remote_src: yes
    dest: /usr/local
  become: yes
  when: not st.stat.exists

- name: Add path to .bashrc & .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    regexp: "export PATH=$PATH:/usr/local/go/bin"
    line: "export PATH=$PATH:/usr/local/go/bin"
  with_items:
  - .bashrc
  - .zshrc

- name: Setup GOPATH in .bashrc & .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    regexp: "export GOPATH=$HOME/go"
    line: "export GOPATH=$HOME/go"
  with_items:
  - .bashrc
  - .zshrc
