
- name: Developer Machine Setup Playbook
  hosts: localhost
  roles:
    - { role: common, become: true }
    - { role: visual-studio-code, become: true }
    - { role: ssh }
    - role: git
      global:
        user.email: himanshun.iitkgp@gmail.com
        user.name: Himanshu Neema
        core.editor: vim
        merge.conflictsytle: diff3



