
- name: Developer Machine Setup Playbook
  hosts: localhost
  roles:
    - role: vim
    - { role: common-packages, become: true }
    - { role: visual-studio-code, become: true }
    - role: ssh
    - role: git
      gitconfig:
        user.email: himanshun.iitkgp@gmail.com
        user.name: Himanshu Neema
        core.editor: vim
        merge.conflictsytle: diff3



