- name: Install Nvidia Driver
  apt:
    name: ["nvidia-dkms-{{ driver_version }}", "nvidia-driver-{{ driver_version }}"]
    update_cache: yes
  register: install  
  become: yes

- debug:
    msg: "Reboot machine manually"
  when: install.changed