- name: Install Nvidia Driver
  apt:
    name: "nvidia-driver-{{ driver_version }}"
    update_cache: yes
  register: install  
  become: yes

- debug:
    msg: "Reboot machine manually"
  when: install.changed