---
# tasks file for git
- name: Install Git
  package:
    name: git
    state: present
  become: yes

- name: Create global gitconfig
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ lookup('dict', gitconfig) }}"
  when: gitconfig is defined