- name: Add apt key for Visual Studio Code
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add apt repository for Visual Studio Code
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
